imports:
    - { resource: functional_testing.yml }
    - { resource: config.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
parameters:
    # This value is used as cache-buster
    asset_version: "dev"

framework:
    translator:
        enabled: true
        fallbacks: [ "%locale%" ]
        paths:
            - '%kernel.project_dir%/languages'
            - '%kernel.project_dir%/theme/base/translations'
            - '%kernel.project_dir%/theme/%theme.name%/translations'
    router:
        resource: "%kernel.project_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

twig:
    cache: false
    auto_reload: true
    debug: true
    strict_variables: false
    paths:
        "%kernel.project_dir%/theme/%theme.name%/templates/modules": theme
        "%kernel.project_dir%/theme/%theme.name%/templates/layouts": themeLayouts
        "%kernel.project_dir%/theme/%theme.name%/images": images
        "%kernel.project_dir%/theme/base/templates/modules": theme
        "%kernel.project_dir%/theme/base/templates/layouts": themeLayouts
        "%kernel.project_dir%/theme/base/images": images
