services:
    _defaults:
        public: true

    engineblock.bridge.error_reporter:
        class: OpenConext\EngineBlockBridge\ErrorReporter
        arguments:
            - "@engineblock.compat.application"
            - "@logger"
            - "@request_stack"

    engineblock.bridge.authentication_logger_adapter:
        class: OpenConext\EngineBlockBridge\Logger\AuthenticationLoggerAdapter
        arguments:
            - "@engineblock.logger.authentication"

    engineblock.bridge.authentication.user_directory:
        class: OpenConext\EngineBlockBridge\Authentication\Repository\UserDirectoryAdapter
        arguments:
            - "@engineblock.authentication.user_directory"
            - "@logger"
