services:

    db.vm.openconext.org:
        image: mariadb:10.6
        restart: always
        container_name: eb-db
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "eb"
            MYSQL_USER: "eb_rw"
            MYSQL_PASSWORD: "secret"
            MYSQL_INITDB_SKIP_TZINFO: 1
        volumes:
            - eb-mysql-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 2s
            retries: 20

    db-test.vm.openconext.org:
        image: mariadb:10.6
        restart: always
        container_name: eb-db-test
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "eb_test"
            MYSQL_USER: "eb_testrw"
            MYSQL_PASSWORD: "secret"
            MYSQL_INITDB_SKIP_TZINFO: 1
        volumes:
            - eb-mysql-test-data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 2s
            retries: 20
            interval: 2s

    web.vm.openconext.org:
        image: ghcr.io/openconext/openconext-basecontainers/php82-apache2-node20-composer2:latest
        volumes:
            - ../:/var/www/html/
            - ./config/apache2.conf:/etc/apache2/sites-enabled/appconf.conf
            - ../ci/qa-config/files/engine.vm.openconext.org.crt:/etc/apache2/ssl/engine.vm.openconext.org.crt
            - ../ci/qa-config/files/engine.vm.openconext.org.key:/etc/apache2/ssl/engine.vm.openconext.org.key
        depends_on:
            db.vm.openconext.org:
                condition: service_healthy
            db-test.vm.openconext.org:
                condition: service_healthy
        extra_hosts:
          - 'engine.vm.openconext.org: 127.0.0.1'
        environment:
          APP_ENV: ci
          SYMFONY_ENV: ci
        networks:
          default:
            aliases:
                - engine.vm.openconext.org


volumes:
    eb-mysql-data:
    eb-mysql-test-data:



